server:
  port: 9100

spring:
  application:
    name: skse-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: dd6f51ca-8481-4e36-9563-3eab3e121664
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: ${spring.cloud.nacos.discovery.namespace}
    sentinel:
      transport:
        dashboard: localhost:9999
        port: 8719
    alibaba:
      seata:
        tx-service-group: skse_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.53.244.217:13307/seata_order
    username: root
    password: -pl,)OKM

logging:
  level:
    com.skse.feign.StorageFeign: debug
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml

feign:
  sentinel:
    enabled: false

ribbon:
  ReadTimeout: 5000
  ConnectTimeou: 5000